// Code generated by services/api/cmd/contractgen. DO NOT EDIT.
//
// The Go types in services/api are authoritative for every shape below
// (ADR-007). To change one, change the Go type and run "make contracts".

import { z } from 'zod';

export const errorCodeSchema = z.enum([
  'not_found',
  'unauthorized',
  'forbidden',
  'conflict',
  'validation',
  'rate_limited',
  'unavailable',
  'internal',
]);

export const healthStatusSchema = z.enum(['healthy', 'degraded', 'unhealthy']);

export const currencySchema = z.enum(['PKR']);

export const merchantQueueSchema = z.enum(['new', 'preparing', 'ready', 'completed', 'cancelled']);

export const issueActionSchema = z.enum(['SUBSTITUTE', 'REMOVE', 'REQUEST_CUSTOMER_DECISION']);

export const groceryOrderStatusSchema = z.enum([
  'CART',
  'PLACED',
  'PAYMENT_PENDING',
  'CONFIRMED',
  'PREPARING',
  'READY_FOR_PICKUP',
  'PICKED_UP',
  'DELIVERING',
  'DELIVERED',
  'CANCELLED',
  'FAILED',
]);

export const eventNameSchema = z.string().regex(/^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+$/);

export const apiErrorBodySchema = z.object({
  code: errorCodeSchema,
  message: z.string(),
  request_id: z.string(),
  details: z.record(z.string(), z.string()).optional(),
});

export const pageInfoSchema = z.object({
  next_cursor: z.string().optional(),
  limit: z.number().int(),
});

export const moneySchema = z.object({
  amount_minor: z.number().int().min(-9007199254740991).max(9007199254740991),
  currency: currencySchema,
});

export const dependencyHealthSchema = z.object({
  name: z.string(),
  status: healthStatusSchema,
  latency_ms: z.number().int(),
  error: z.string().optional(),
});

export const healthResponseSchema = z.object({
  status: healthStatusSchema,
  service: z.string(),
  version: z.string(),
  checked_at: z.string().datetime({ offset: true }),
  dependencies: z.array(dependencyHealthSchema),
});

export const analyticsEventSchema = z.object({
  event_id: z.string(),
  event_name: eventNameSchema,
  actor_id: z.string().optional(),
  anonymous_id: z.string().optional(),
  timestamp: z.string().datetime({ offset: true }),
  source: z.string(),
  session_id: z.string().optional(),
  correlation_id: z.string().optional(),
  properties: z.record(z.string(), z.unknown()).optional(),
});

export const jobStopSchema = z.object({
  id: z.string(),
  sequence: z.number().int(),
  type: z.string(),
  latitude: z.number(),
  longitude: z.number(),
  address: z.string().optional(),
});

export const jobSchema = z.object({
  id: z.string(),
  type: z.string(),
  status: z.string(),
  stops: z.array(jobStopSchema),
  quote_id: z.string().optional(),
  assigned_driver_id: z.string().optional(),
  scheduled_at: z.string().datetime({ offset: true }).optional(),
  created_at: z.string().datetime({ offset: true }),
});

export const quoteLineSchema = z.object({
  component: z.string(),
  amount: moneySchema,
  detail: z.string().optional(),
});

export const quoteSchema = z.object({
  quote_id: z.string(),
  total: moneySchema,
  lines: z.array(quoteLineSchema),
  distance_meters: z.number().int(),
  duration_seconds: z.number().int(),
  route_confidence: z.string(),
  expires_at: z.string().datetime({ offset: true }),
});

export const cancelResultSchema = z.object({
  job: jobSchema,
  cancellation_tier: z.string(),
  fee: moneySchema,
});

export const driverProfileSchema = z.object({
  id: z.string(),
  status: z.string(),
  active_vehicle_id: z.string().optional(),
  verification_status: z.string(),
});

export const rejectedFixSchema = z.object({
  recorded_at: z.string().datetime({ offset: true }),
  reason: z.string(),
  detail: z.string().optional(),
});

export const locationReportSchema = z.object({
  accepted: z.number().int(),
  rejected: z.array(rejectedFixSchema),
});

export const driverAssignmentSchema = z.object({
  id: z.string(),
  status: z.string(),
  offered_at: z.string().datetime({ offset: true }),
  expires_at: z.string().datetime({ offset: true }).optional(),
  job: jobSchema,
});

export const pointSchema = z.object({
  lat: z.number(),
  lon: z.number(),
});

export const placeSchema = z.object({
  provider_id: z.string().optional(),
  name: z.string(),
  address: z.string(),
  point: pointSchema,
});

export const earningsTotalSchema = z.object({
  net: moneySchema,
  trips: z.number().int(),
  from: z.string().datetime({ offset: true }),
  to: z.string().datetime({ offset: true }),
});

export const tripEarningSchema = z.object({
  job_id: z.string(),
  amount: moneySchema,
  at: z.string().datetime({ offset: true }),
});

export const driverEarningsSchema = z.object({
  today: earningsTotalSchema,
  week: earningsTotalSchema,
  trips: z.array(tripEarningSchema),
});

export const merchantOrderItemSchema = z.object({
  id: z.string(),
  name: z.string(),
  quantity: z.number().int(),
  unit_price: moneySchema,
  line_total: moneySchema,
  substitution_preference: z.string(),
  status: z.string(),
});

export const merchantOrderIssueSchema = z.object({
  id: z.string(),
  order_item_id: z.string(),
  reason: z.string(),
  action: z.string(),
  resolution: z.string(),
  substitute_name: z.string().optional(),
  substitute_price: moneySchema.optional(),
  price_difference: moneySchema.optional(),
  created_at: z.string().datetime({ offset: true }),
});

export const merchantOrderSchema = z.object({
  id: z.string(),
  status: z.string(),
  items_total: moneySchema,
  accept_deadline: z.string().datetime({ offset: true }).optional(),
  accepted_at: z.string().datetime({ offset: true }).optional(),
  preparation_started_at: z.string().datetime({ offset: true }).optional(),
  expected_ready_at: z.string().datetime({ offset: true }).optional(),
  rejection_reason: z.string().optional(),
  created_at: z.string().datetime({ offset: true }),
  items: z.array(merchantOrderItemSchema).optional(),
  job_id: z.string().optional(),
  issues: z.array(merchantOrderIssueSchema).optional(),
});
