// Code generated by services/api/cmd/contractgen. DO NOT EDIT.
//
// The Go types in services/api are authoritative for every shape below
// (ADR-007). To change one, change the Go type and run "make contracts".

export const ERROR_CODES = [
  'not_found',
  'unauthorized',
  'forbidden',
  'conflict',
  'validation',
  'rate_limited',
  'unavailable',
  'internal',
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];

export const HEALTH_STATUSES = ['healthy', 'degraded', 'unhealthy'] as const;

export type HealthStatus = (typeof HEALTH_STATUSES)[number];

export const CURRENCIES = ['PKR'] as const;

export type Currency = (typeof CURRENCIES)[number];

export const MERCHANT_QUEUES = ['new', 'preparing', 'ready', 'completed', 'cancelled'] as const;

export type MerchantQueue = (typeof MERCHANT_QUEUES)[number];

export const ISSUE_ACTIONS = ['SUBSTITUTE', 'REMOVE', 'REQUEST_CUSTOMER_DECISION'] as const;

export type IssueAction = (typeof ISSUE_ACTIONS)[number];

export const GROCERY_ORDER_STATUSES = [
  'CART',
  'PLACED',
  'PAYMENT_PENDING',
  'CONFIRMED',
  'PREPARING',
  'READY_FOR_PICKUP',
  'PICKED_UP',
  'DELIVERING',
  'DELIVERED',
  'CANCELLED',
  'FAILED',
] as const;

export type GroceryOrderStatus = (typeof GROCERY_ORDER_STATUSES)[number];

export type EventName = string;

export interface ApiErrorBody {
  code: ErrorCode;
  message: string;
  request_id: string;
  details?: Record<string, string> | undefined;
}

export interface PageInfo {
  next_cursor?: string | undefined;
  limit: number;
}

export interface Money {
  amount_minor: number;
  currency: Currency;
}

export interface DependencyHealth {
  name: string;
  status: HealthStatus;
  latency_ms: number;
  error?: string | undefined;
}

export interface HealthResponse {
  status: HealthStatus;
  service: string;
  version: string;
  checked_at: string;
  dependencies: DependencyHealth[];
}

export interface AnalyticsEvent {
  event_id: string;
  event_name: EventName;
  actor_id?: string | undefined;
  anonymous_id?: string | undefined;
  timestamp: string;
  source: string;
  session_id?: string | undefined;
  correlation_id?: string | undefined;
  properties?: Record<string, unknown> | undefined;
}

export interface JobStop {
  id: string;
  sequence: number;
  type: string;
  latitude: number;
  longitude: number;
  address?: string | undefined;
}

export interface Job {
  id: string;
  type: string;
  status: string;
  stops: JobStop[];
  quote_id?: string | undefined;
  assigned_driver_id?: string | undefined;
  scheduled_at?: string | undefined;
  created_at: string;
}

export interface QuoteLine {
  component: string;
  amount: Money;
  detail?: string | undefined;
}

export interface Quote {
  quote_id: string;
  total: Money;
  lines: QuoteLine[];
  distance_meters: number;
  duration_seconds: number;
  route_confidence: string;
  expires_at: string;
}

export interface CancelResult {
  job: Job;
  cancellation_tier: string;
  fee: Money;
}

export interface DriverProfile {
  id: string;
  status: string;
  active_vehicle_id?: string | undefined;
  verification_status: string;
}

export interface RejectedFix {
  recorded_at: string;
  reason: string;
  detail?: string | undefined;
}

export interface LocationReport {
  accepted: number;
  rejected: RejectedFix[];
}

export interface DriverAssignment {
  id: string;
  status: string;
  offered_at: string;
  expires_at?: string | undefined;
  job: Job;
}

export interface Point {
  lat: number;
  lon: number;
}

export interface Place {
  provider_id?: string | undefined;
  name: string;
  address: string;
  point: Point;
}

export interface EarningsTotal {
  net: Money;
  trips: number;
  from: string;
  to: string;
}

export interface TripEarning {
  job_id: string;
  amount: Money;
  at: string;
}

export interface DriverEarnings {
  today: EarningsTotal;
  week: EarningsTotal;
  trips: TripEarning[];
}

export interface MerchantOrderItem {
  id: string;
  name: string;
  quantity: number;
  unit_price: Money;
  line_total: Money;
  substitution_preference: string;
  status: string;
}

export interface MerchantOrderIssue {
  id: string;
  order_item_id: string;
  reason: string;
  action: string;
  resolution: string;
  substitute_name?: string | undefined;
  substitute_price?: Money | undefined;
  price_difference?: Money | undefined;
  created_at: string;
}

export interface MerchantOrder {
  id: string;
  status: string;
  items_total: Money;
  accept_deadline?: string | undefined;
  accepted_at?: string | undefined;
  preparation_started_at?: string | undefined;
  expected_ready_at?: string | undefined;
  rejection_reason?: string | undefined;
  created_at: string;
  items?: MerchantOrderItem[] | undefined;
  job_id?: string | undefined;
  issues?: MerchantOrderIssue[] | undefined;
}
