// Code generated by services/api/cmd/contractgen. DO NOT EDIT.
//
// The Go types in services/api are authoritative for every shape below
// (ADR-007). To change one, change the Go type and run "make contracts".

export const ERROR_CODES = [
  'not_found',
  'unauthorized',
  'forbidden',
  'conflict',
  'validation',
  'rate_limited',
  'unavailable',
  'internal',
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];

export const HEALTH_STATUSES = ['healthy', 'degraded', 'unhealthy'] as const;

export type HealthStatus = (typeof HEALTH_STATUSES)[number];

export const CURRENCIES = ['PKR'] as const;

export type Currency = (typeof CURRENCIES)[number];

export type EventName = string;

export interface ApiErrorBody {
  code: ErrorCode;
  message: string;
  request_id: string;
  details?: Record<string, string> | undefined;
}

export interface PageInfo {
  next_cursor?: string | undefined;
  limit: number;
}

export interface Money {
  amount_minor: number;
  currency: Currency;
}

export interface DependencyHealth {
  name: string;
  status: HealthStatus;
  latency_ms: number;
  error?: string | undefined;
}

export interface HealthResponse {
  status: HealthStatus;
  service: string;
  version: string;
  checked_at: string;
  dependencies: DependencyHealth[];
}

export interface AnalyticsEvent {
  event_id: string;
  event_name: EventName;
  actor_id?: string | undefined;
  anonymous_id?: string | undefined;
  timestamp: string;
  source: string;
  session_id?: string | undefined;
  correlation_id?: string | undefined;
  properties?: Record<string, unknown> | undefined;
}
